import './styles.css';
import { assets, products, ingredients, reviews, contact } from './data/siteData.js';

const icon = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2"/><path d="M12 8V16M8 12H16" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
const viewer = (className, src, orbit, extra = '') => `<model-viewer class="${className}" src="${src}" environment-image="neutral" exposure="1.2" interaction-prompt="none" camera-orbit="${orbit}" ${extra}></model-viewer>`;
const header = document.querySelector('[data-header]');
header.innerHTML = `<a class="logo" href="#home">${icon}<span>Soda</span></a><button class="mobile-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nav glass" data-nav>${['Home','Ingredients','Taste','Eco','Reviews'].map(x => `<a class="nav-item ${x === 'Home' ? 'active' : ''}" href="#${x.toLowerCase()}">${x}</a>`).join('')}</nav><a class="contact-btn" href="#contact">Contact Us</a>`;
const cards = products.map((p, i) => `<button class="card ${i === 0 ? 'active' : ''}" data-flavor="${p.id}"><img src="${p.image}" alt="${p.name}" ${i ? 'style="filter:brightness(.7)"' : ''}><span class="card-info"><strong>${p.name}</strong><small>${p.price}</small></span></button>`).join('');
document.querySelector('#home').innerHTML = `<div class="hero-content"><div class="leaves-container">${[['l1','45deg 75deg 105%'],['l2','-30deg 60deg 105%'],['l3','120deg 85deg 105%'],['l4','10deg 45deg 105%']].map(([c,o]) => viewer(`leaf ${c}`, assets.leaves, o)).join('')}</div><div class="hero-left"><h1 class="main-title"><span>Pure</span><br>Zero</h1><p class="description">Unleash the crisp taste of zero sugar.<br>Refreshment redefined in every bubble —<br>all in one sleek design.</p><button class="primary-btn" data-scroll="#taste">Shop Now <b>+</b></button><div class="award-badge"><span class="award-icon">${icon}</span><span><small>DESIGN AWARDS</small><strong>PREMIUM BEVERAGE 2025</strong></span></div></div><div class="berries-container-bg">${[['b7','-20deg 110deg 105%'],['b8','160deg 45deg 105%'],['b9','45deg 20deg 105%']].map(([c,o]) => viewer(`berry ${c}`, assets.cherry, o)).join('')}</div><div class="hero-center"><model-viewer id="product-model" src="${assets.can}" alt="Diet Soda 3D Model" camera-controls disable-zoom shadow-intensity="0" environment-image="neutral" exposure="1.5" interaction-prompt="none" camera-orbit="0deg 90deg 380%" field-of-view="30deg" class="main-product-3d"></model-viewer></div><div class="berries-container">${[['b1','45deg 120deg 105%'],['b2','-120deg 45deg 105%'],['b3','200deg 90deg 105%'],['b4','10deg 20deg 105%'],['b5','-45deg 160deg 105%'],['b6','80deg 75deg 105%']].map(([c,o]) => viewer(`berry ${c}`, assets.cherry, o)).join('')}</div><div class="hero-right"><div class="product-carousel"><div class="carousel-cards">${cards}</div><div class="carousel-nav"><button class="nav-arrow" data-prev>←</button><button class="nav-arrow" data-next>→</button></div></div><h2 class="side-title"><span>Refreshingly</span><br>Clean</h2></div></div>`;
document.querySelector('#ingredients').innerHTML = `<div class="section-heading reveal"><span class="eyebrow">Inside the bubble</span><h2>Thoughtfully<br><em>made.</em></h2><p>Every detail is designed around a crisp, clean refreshment ritual.</p></div><div class="ingredient-rail">${ingredients.map(x => `<article class="ingredient-card glass reveal"><span>${x.number}</span><h3>${x.name}</h3><p>${x.copy}</p></article>`).join('')}</div>`;
document.querySelector('#taste').innerHTML = `<div class="taste-copy reveal"><span class="eyebrow">Find your flavor</span><h2>Two moods.<br><em>One pure pour.</em></h2><p>Switch between the familiar depth of Diet Classic and the bright lift of Zero Lime. Choose a card above or explore here.</p><div class="taste-actions">${products.map(p => `<button class="outline-btn" data-flavor="${p.id}">${p.name} <span>↗</span></button>`).join('')}</div></div><div class="taste-orbit">${viewer('taste-berry', assets.cherry, '45deg 120deg 105%')}<span class="orbit-ring"></span></div>`;
document.querySelector('#eco').innerHTML = `<div class="eco-panel glass reveal"><span class="eyebrow">A lighter way forward</span><h2>Good taste<br><em>with intention.</em></h2><p>Our sustainability story is an evolving work in progress. This space is ready for your verified packaging and sourcing commitments.</p><span class="status-chip">EXPERIMENTAL / DATA-READY</span></div><div class="eco-stat reveal"><strong>01</strong><span>Designing for a more considered everyday refreshment.</span></div>`;
document.querySelector('#reviews').innerHTML = `<div class="section-heading reveal"><span class="eyebrow">The good word</span><h2>Fresh takes<br><em>from the community.</em></h2></div><div class="review-track">${reviews.map(r => `<article class="review-card glass reveal"><div class="review-person"><img src="${r.image}" alt="Placeholder portrait for ${r.name}"><span><strong>${r.name}</strong><small>${'★'.repeat(r.rating)}</small></span></div><p>“${r.copy}”</p></article>`).join('')}</div>`;
document.querySelector('#contact').innerHTML = `<div class="contact-intro reveal"><span class="eyebrow">Start a conversation</span><h2>Let’s keep it<br><em>refreshing.</em></h2><div class="contact-links"><a href="mailto:${contact.email}">${contact.email}</a><a href="tel:${contact.phone.replaceAll(' ','')}">${contact.phone}</a><span><a href="${contact.instagram}">Instagram</a> <a href="${contact.facebook}">Facebook</a> <a href="${contact.whatsapp}">WhatsApp</a></span></div></div><form class="contact-form glass reveal"><label>Name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" type="email" required placeholder="you@example.com"></label><label>Message<textarea name="message" required placeholder="How can we help?"></textarea></label><button class="primary-btn" type="submit">Send message <b>+</b></button><p class="form-note" role="status"></p></form>`;

const can = document.querySelector('#product-model'); const fg = document.querySelector('.berries-container'); const bg = document.querySelector('.berries-container-bg'); const leaves = document.querySelector('.leaves-container'); const berryNodes = [...document.querySelectorAll('.berry')]; let switching = false, spin = 0;
const applyFlavor = async flavor => { if (switching) return; switching = true; document.body.classList.toggle('blue-theme', flavor === 'blue'); gsap.to(document.body, {'--bg-inner': flavor === 'blue' ? '#0b4f8a' : '#0b8a78','--bg-mid': flavor === 'blue' ? '#04294e' : '#044e3b','--bg-outer': flavor === 'blue' ? '#010c14' : '#011411', duration: 1.5, ease: 'power2.inOut'}); gsap.to({ value: 0 }, { value: 720, duration: 2.1, ease: 'power2.inOut', onUpdate: function(){ spin = this.targets()[0].value; can.style.filter = `blur(${Math.max(0, 15 - spin / 48)}px)`; }, onComplete(){ spin = 0; can.style.filter = 'none'; }}); berryNodes.forEach((b, i) => { const targetX = (innerWidth / 2) - b.offsetLeft - b.offsetWidth / 2; const targetY = (innerHeight / 2) - b.offsetTop - b.offsetHeight / 2; gsap.timeline().to(b,{x:targetX,y:targetY,scale:.1,opacity:0,duration:.5,ease:'power2.in'}).to(b,{duration:.3}).to(b,{x:(Math.random()-.5)*200,y:(Math.random()-.5)*200,scale:1,opacity:1,duration:.9,ease:'back.out(1.5)',onStart(){b.src=flavor==='blue'?assets.blueberry:assets.cherry},onComplete(){if(i===berryNodes.length-1)switching=false}}); }); };
const syncCards = flavor => { document.querySelectorAll('[data-flavor]').forEach(el => { if (el.classList.contains('card')) el.classList.toggle('active', el.dataset.flavor === flavor); }); applyFlavor(flavor); };
document.querySelectorAll('[data-flavor]').forEach(el => el.addEventListener('click', () => syncCards(el.dataset.flavor)));
document.querySelector('[data-next]').addEventListener('click', () => syncCards(document.querySelector('.card.active').dataset.flavor === 'classic' ? 'blue' : 'classic'));
document.querySelector('[data-prev]').addEventListener('click', () => syncCards(document.querySelector('.card.active').dataset.flavor === 'classic' ? 'blue' : 'classic'));
let mouse = {x:0,y:0,px:innerWidth/2,py:innerHeight/2}, current = {x:0,y:0}; addEventListener('mousemove', e => { mouse.x=e.clientX/innerWidth-.5; mouse.y=e.clientY/innerHeight-.5; mouse.px=e.clientX; mouse.py=e.clientY; });
function animate(){ const t=performance.now()*.001; current.x+=(mouse.x-current.x)*.05; current.y+=(mouse.y-current.y)*.05; can.cameraOrbit=`${current.x*40+spin}deg ${90+current.y*20}deg 380%`; fg.style.transform=`translate(${current.x*60}px,${current.y*60}px)`; bg.style.transform=`translate(${current.x*-30}px,${current.y*-30}px)`; leaves.style.transform=`translate(${current.x*-15}px,${current.y*-15}px)`; if(!switching) berryNodes.forEach((b,i)=>{const r=b.getBoundingClientRect(),dx=mouse.px-r.left-r.width/2,dy=mouse.py-r.top-r.height/2,d=Math.max(1,Math.hypot(dx,dy)),f=d<400?(400-d)/400:0,x=(+b.dataset.rx||0)+(dx/d*f*-80-(+b.dataset.rx||0))*.1,y=(+b.dataset.ry||0)+(dy/d*f*-80-(+b.dataset.ry||0))*.1,a=(+b.dataset.angle||0)+.2*(1+f*5); b.dataset.rx=x;b.dataset.ry=y;b.dataset.angle=a; const phase=(t+i*.7)*Math.PI*2/[5,7,6,8,5.5,6.5,9,11,10][i%9]; b.style.transform=`translate(${x}px,${y+Math.sin(phase)*15}px) rotate(${a+Math.cos(phase)*6}deg)`}); document.querySelectorAll('.leaf').forEach((l,i)=>{const p=(t+i*1.2)*Math.PI*2/(10+i);l.style.transform=`translate(${Math.cos(p*.5)*15}px,${Math.sin(p)*20}px) rotate(${Math.sin(p*.3)*15}deg)`}); requestAnimationFrame(animate); } berryNodes.forEach(b=>{b.dataset.rx=0;b.dataset.ry=0;b.dataset.angle=Math.random()*360}); animate();
const bubbleBox=document.querySelector('#bubbles-container'); setInterval(()=>{const b=document.createElement('img');b.src=assets.bubble;b.className='bubble-img';const d=Math.random()*6+4;b.style.width=`${Math.random()*20+10}px`;b.style.left=`${Math.random()*100}%`;b.style.bottom='-50px';b.style.animation=`floatUpImg ${d}s linear forwards`;bubbleBox.appendChild(b);setTimeout(()=>b.remove(),d*1000)},400);
const toggle=document.querySelector('.mobile-toggle');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));document.querySelector('[data-nav]').classList.toggle('open',!open)}); document.querySelectorAll('a[href^="#"], [data-scroll]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href')||a.dataset.scroll;e.preventDefault();document.querySelector(id)?.scrollIntoView({behavior:'smooth'});document.querySelector('[data-nav]').classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el)); document.querySelector('.contact-form').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-note').textContent='Thanks — your message is ready to be connected.';e.currentTarget.reset()});
